package br.gov.mandaguari.saude.pessoa.dto;

import java.time.LocalDate;

/** DTOs for the Pessoa read API. No secrets (PesSenha/PesSenhaKey are unmapped/quarantined). */
public final class PessoaDtos {
    private PessoaDtos() {}

    /**
     * Person read projection. {@code nomeExibicao}/{@code nomeCompleto} apply the social-name rule
     * (R2/R3) — consumers (UI/reports) MUST display {@code nomeExibicao}, never the raw registry name,
     * when {@code usaNomeSocial} (LGPD / Decreto 8.727/2016).
     */
    public record PessoaResponse(
            Long id,
            String nome,
            String nomeSocial,
            boolean usaNomeSocial,
            String nomeExibicao,
            String nomeCompleto,
            String cpfCnpj,
            String cns,
            LocalDate dataNascimento,
            String sexo,
            String telefone,
            String celular,
            String email) {}

    /** Slim lookup item — shows the LGPD-correct display name only. */
    public record PessoaLookupItem(Long id, String nomeExibicao) {}

    /**
     * Full person cadastro write payload (SAU_PESF). No {@code id} (generated on create / path on update),
     * no soundex (derived), no credentials (PesSenha quarantined). All the mined validations run in the
     * service with the legacy PT-BR messages/codes — this record is a plain carrier.
     */
    public record PessoaCadastroRequest(
            String nome,
            String nomeSocial,
            Boolean usaNomeSocial,
            String nomePai,
            String nomeMae,
            String nomeConjuge,
            String cpfCnpj,
            String cns,
            String rgIe,
            Integer orgaoEmissorCod,
            String rgUf,
            LocalDate rgDataEmissao,
            LocalDate dataNascimento,
            String sexo,
            Integer corCod,
            Integer estadoCivilCod,
            Integer situacaoFamiliarCod,
            Integer etniaCod,
            String tipoSanguineo,
            Integer nacionalidadeTipo,
            Integer paisCod,
            Integer municipioNascCod,
            LocalDate dataNaturalizacao,
            String numeroPortaria,
            LocalDate dataEntradaPais,
            String cep,
            Integer tipoLogradouroCod,
            String endereco,
            String enderecoNumero,
            String enderecoComplemento,
            Integer bairroCod,
            Integer municipioCod,
            String telefone,
            String celular,
            String fax,
            String email,
            String homePage,
            Integer certidaoCivilTipo,
            String certidaoNumero,
            String certidaoLivro,
            String certidaoFolha,
            LocalDate certidaoData,
            String certidaoCartorio,
            String ctpsSerie,
            String ctpsNumero,
            String ctpsUf,
            LocalDate ctpsData,
            String pisPasep,
            String tituloEleitorNumero,
            String tituloEleitorZona,
            String tituloEleitorSecao,
            String nis,
            String frequentaEscola,
            Integer grauEscolaridade,
            Integer escolaridade,
            String cboCod,
            String observacao,
            Integer gerarBpa) {}

    /** Full cadastro read-back (PHI — SAUDE_CADASTRO only). Echoes the persisted person. */
    public record PessoaCadastroResponse(
            Long id,
            Integer tipoPessoa,
            String nome,
            String nomeSocial,
            boolean usaNomeSocial,
            String nomeExibicao,
            String nomePai,
            String nomeMae,
            String nomeConjuge,
            String cpfCnpj,
            String cns,
            String rgIe,
            Integer orgaoEmissorCod,
            String rgUf,
            LocalDate rgDataEmissao,
            LocalDate dataNascimento,
            String sexo,
            Integer corCod,
            Integer estadoCivilCod,
            Integer situacaoFamiliarCod,
            Integer etniaCod,
            String tipoSanguineo,
            Integer nacionalidadeTipo,
            Integer paisCod,
            Integer municipioNascCod,
            LocalDate dataNaturalizacao,
            String numeroPortaria,
            LocalDate dataEntradaPais,
            String cep,
            Integer tipoLogradouroCod,
            String endereco,
            String enderecoNumero,
            String enderecoComplemento,
            Integer bairroCod,
            Integer municipioCod,
            String telefone,
            String celular,
            String fax,
            String email,
            String homePage,
            Integer certidaoCivilTipo,
            String certidaoNumero,
            String certidaoLivro,
            String certidaoFolha,
            LocalDate certidaoData,
            String certidaoCartorio,
            String ctpsSerie,
            String ctpsNumero,
            String ctpsUf,
            LocalDate ctpsData,
            String pisPasep,
            String tituloEleitorNumero,
            String tituloEleitorZona,
            String tituloEleitorSecao,
            String nis,
            String frequentaEscola,
            Integer grauEscolaridade,
            Integer escolaridade,
            String cboCod,
            LocalDate dataCadastro,
            String observacao,
            Integer gerarBpa) {}
}
