package br.gov.mandaguari.saude.usuariounidade.dto;

/** DTOs for the SAU_USUUNI capability matrix. All 54 flags are booleans; usuCod/uniCod come from the path. */
public final class UsuarioUnidadeDtos {
    private UsuarioUnidadeDtos() {}

    /** One (user, unit) capability row. */
    public record UsuarioUnidadeResponse(
            Integer usuCod,
            Integer uniCod,
            Integer especialidadeCod,
            Boolean bloqueioTabela,
            Boolean bloqueioCadastro,
            Boolean bloqueioAmbulatorio,
            Boolean permiteConsultaDireta,
            Boolean bloqueioProntuarioConsulta,
            Boolean bloqueioProntuarioOdonto,
            Boolean bloqueioResultadoExame,
            Boolean bloqueioEsus,
            Boolean bloqueioCaps,
            Boolean bloqueioNutricao,
            Boolean bloqueioFarmacia,
            Boolean permiteBnafar,
            Boolean bloqueioAlmoxarifado,
            Boolean bloqueioRequisicao,
            Boolean bloqueioBeneficio,
            Boolean bloqueioTransporte,
            Boolean bloqueioVacina,
            Boolean bloqueioAgenda,
            Boolean bloqueioAgendaManual,
            Boolean bloqueioAgendaExterna,
            Boolean bloqueioAgendaEspecial,
            Boolean permiteAgendaAuditor,
            Boolean bloqueioLaboratorio,
            Boolean bloqueioHospital,
            Boolean bloqueioVigilancia,
            Boolean bloqueioAgravo,
            Boolean bloqueioCms,
            Boolean bloqueioOuvidoria,
            Boolean bloqueioImpressao,
            Boolean bloqueioExportacao,
            Boolean bloqueioParametro,
            Boolean bloqueioRelatorio,
            Boolean bloqueioRelatorioTabela,
            Boolean bloqueioRelatorioCadastro,
            Boolean bloqueioRelatorioAmbulatorio,
            Boolean bloqueioRelatorioEsus,
            Boolean bloqueioRelatorioCaps,
            Boolean bloqueioRelatorioNutricao,
            Boolean bloqueioRelatorioVacina,
            Boolean bloqueioRelatorioFarmacia,
            Boolean bloqueioRelatorioAlmoxarifado,
            Boolean bloqueioRelatorioRequisicao,
            Boolean bloqueioRelatorioBeneficio,
            Boolean bloqueioRelatorioTransporte,
            Boolean bloqueioRelatorioAgenda,
            Boolean bloqueioRelatorioLaboratorio,
            Boolean bloqueioRelatorioHospital,
            Boolean bloqueioRelatorioVigilancia,
            Boolean bloqueioRelatorioAgravo,
            Boolean bloqueioRelatorioOuvidoria,
            Boolean bloqueioRelatorioExportacao,
            Boolean bloqueioGrafico,
            Boolean permiteAgendaAuditorPcd,
            Boolean permiteSoaBnafar) {}

    /** Grant a user access to a unit, or replace the flags of an existing (user, unit) row. */
    public record UsuarioUnidadeUpsertRequest(
            Integer especialidadeCod,
            Boolean bloqueioTabela,
            Boolean bloqueioCadastro,
            Boolean bloqueioAmbulatorio,
            Boolean permiteConsultaDireta,
            Boolean bloqueioProntuarioConsulta,
            Boolean bloqueioProntuarioOdonto,
            Boolean bloqueioResultadoExame,
            Boolean bloqueioEsus,
            Boolean bloqueioCaps,
            Boolean bloqueioNutricao,
            Boolean bloqueioFarmacia,
            Boolean permiteBnafar,
            Boolean bloqueioAlmoxarifado,
            Boolean bloqueioRequisicao,
            Boolean bloqueioBeneficio,
            Boolean bloqueioTransporte,
            Boolean bloqueioVacina,
            Boolean bloqueioAgenda,
            Boolean bloqueioAgendaManual,
            Boolean bloqueioAgendaExterna,
            Boolean bloqueioAgendaEspecial,
            Boolean permiteAgendaAuditor,
            Boolean bloqueioLaboratorio,
            Boolean bloqueioHospital,
            Boolean bloqueioVigilancia,
            Boolean bloqueioAgravo,
            Boolean bloqueioCms,
            Boolean bloqueioOuvidoria,
            Boolean bloqueioImpressao,
            Boolean bloqueioExportacao,
            Boolean bloqueioParametro,
            Boolean bloqueioRelatorio,
            Boolean bloqueioRelatorioTabela,
            Boolean bloqueioRelatorioCadastro,
            Boolean bloqueioRelatorioAmbulatorio,
            Boolean bloqueioRelatorioEsus,
            Boolean bloqueioRelatorioCaps,
            Boolean bloqueioRelatorioNutricao,
            Boolean bloqueioRelatorioVacina,
            Boolean bloqueioRelatorioFarmacia,
            Boolean bloqueioRelatorioAlmoxarifado,
            Boolean bloqueioRelatorioRequisicao,
            Boolean bloqueioRelatorioBeneficio,
            Boolean bloqueioRelatorioTransporte,
            Boolean bloqueioRelatorioAgenda,
            Boolean bloqueioRelatorioLaboratorio,
            Boolean bloqueioRelatorioHospital,
            Boolean bloqueioRelatorioVigilancia,
            Boolean bloqueioRelatorioAgravo,
            Boolean bloqueioRelatorioOuvidoria,
            Boolean bloqueioRelatorioExportacao,
            Boolean bloqueioGrafico,
            Boolean permiteAgendaAuditorPcd,
            Boolean permiteSoaBnafar) {}
}
