-- SAU_PESF (Pessoa Física) — write-enable the SYS_PES person supertype.
-- Adds the full person-cadastro columns the SAU_PESF transaction writes (INSERT T000X24 in
-- sau_pesf_impl.java:9502). Types verified against the LIVE PostgreSQL (introspected 2026-06-30):
-- the real/parity DB already has all 86 columns, so every statement is a no-op there; these ALTERs
-- only build up the local docker DB / Testcontainers schema so ddl-auto=validate passes.
-- Idempotent (ADD COLUMN IF NOT EXISTS). Names/types pinned to the physical schema. No NOT NULL added
-- (live has none beyond the PK). Quarantined credential columns (PesSenha/PesSenhaKey) and the
-- establishment/PJ block are intentionally NOT added — this slice does not map them.

ALTER TABLE SYS_PES ADD COLUMN IF NOT EXISTS PesTip           SMALLINT;
ALTER TABLE SYS_PES ADD COLUMN IF NOT EXISTS PesNomPai        VARCHAR(50);
ALTER TABLE SYS_PES ADD COLUMN IF NOT EXISTS PesNomMae        VARCHAR(50);
ALTER TABLE SYS_PES ADD COLUMN IF NOT EXISTS PesNomCon        VARCHAR(50);
ALTER TABLE SYS_PES ADD COLUMN IF NOT EXISTS PesNomMaeSoundex VARCHAR(50);
ALTER TABLE SYS_PES ADD COLUMN IF NOT EXISTS PesNomSocSoundex VARCHAR(50);
ALTER TABLE SYS_PES ADD COLUMN IF NOT EXISTS PesRGIE          VARCHAR(15);
ALTER TABLE SYS_PES ADD COLUMN IF NOT EXISTS PesOrgEmiCod     INTEGER;
ALTER TABLE SYS_PES ADD COLUMN IF NOT EXISTS PesIdeEst        CHAR(2);
ALTER TABLE SYS_PES ADD COLUMN IF NOT EXISTS PesIdeDat        DATE;
ALTER TABLE SYS_PES ADD COLUMN IF NOT EXISTS PesCor           SMALLINT;
ALTER TABLE SYS_PES ADD COLUMN IF NOT EXISTS PesEstCiv        SMALLINT;
ALTER TABLE SYS_PES ADD COLUMN IF NOT EXISTS PesSitFam        SMALLINT;
ALTER TABLE SYS_PES ADD COLUMN IF NOT EXISTS PesEtnCod        SMALLINT;
ALTER TABLE SYS_PES ADD COLUMN IF NOT EXISTS PesTipSan        CHAR(3);
ALTER TABLE SYS_PES ADD COLUMN IF NOT EXISTS PesNacTip        SMALLINT;
ALTER TABLE SYS_PES ADD COLUMN IF NOT EXISTS PesPaisCod       SMALLINT;
ALTER TABLE SYS_PES ADD COLUMN IF NOT EXISTS PesNacMunCod     INTEGER;
ALTER TABLE SYS_PES ADD COLUMN IF NOT EXISTS PesNacDatNat     DATE;
ALTER TABLE SYS_PES ADD COLUMN IF NOT EXISTS PesNacNumPor     VARCHAR(16);
ALTER TABLE SYS_PES ADD COLUMN IF NOT EXISTS PesNacDatEnt     DATE;
ALTER TABLE SYS_PES ADD COLUMN IF NOT EXISTS PesCEP           CHAR(8);
ALTER TABLE SYS_PES ADD COLUMN IF NOT EXISTS PesTipLogCod     INTEGER;
ALTER TABLE SYS_PES ADD COLUMN IF NOT EXISTS PesEnd           VARCHAR(70);
ALTER TABLE SYS_PES ADD COLUMN IF NOT EXISTS PesEndNum        VARCHAR(10);
ALTER TABLE SYS_PES ADD COLUMN IF NOT EXISTS PesEndCom        VARCHAR(40);
ALTER TABLE SYS_PES ADD COLUMN IF NOT EXISTS PesMunCod        INTEGER;
ALTER TABLE SYS_PES ADD COLUMN IF NOT EXISTS PesFax           VARCHAR(20);
ALTER TABLE SYS_PES ADD COLUMN IF NOT EXISTS PesHomePage      VARCHAR(70);
ALTER TABLE SYS_PES ADD COLUMN IF NOT EXISTS PesCerCiv        SMALLINT;
ALTER TABLE SYS_PES ADD COLUMN IF NOT EXISTS PesCerNum        VARCHAR(8);
ALTER TABLE SYS_PES ADD COLUMN IF NOT EXISTS PesCerLiv        VARCHAR(8);
ALTER TABLE SYS_PES ADD COLUMN IF NOT EXISTS PesCerFol        VARCHAR(4);
ALTER TABLE SYS_PES ADD COLUMN IF NOT EXISTS PesCerDat        DATE;
ALTER TABLE SYS_PES ADD COLUMN IF NOT EXISTS PesCerCar        VARCHAR(60);
ALTER TABLE SYS_PES ADD COLUMN IF NOT EXISTS PesNovCerSer     VARCHAR(6);
ALTER TABLE SYS_PES ADD COLUMN IF NOT EXISTS PesNovCerAce     VARCHAR(2);
ALTER TABLE SYS_PES ADD COLUMN IF NOT EXISTS PesNovCerRegCiv  VARCHAR(2);
ALTER TABLE SYS_PES ADD COLUMN IF NOT EXISTS PesNovCerAno     VARCHAR(4);
ALTER TABLE SYS_PES ADD COLUMN IF NOT EXISTS PesNovCerTipLiv  CHAR(1);
ALTER TABLE SYS_PES ADD COLUMN IF NOT EXISTS PesNovCerLiv     VARCHAR(5);
ALTER TABLE SYS_PES ADD COLUMN IF NOT EXISTS PesNovCerFol     VARCHAR(3);
ALTER TABLE SYS_PES ADD COLUMN IF NOT EXISTS PesNovCerTer     VARCHAR(7);
ALTER TABLE SYS_PES ADD COLUMN IF NOT EXISTS PesNovCerDv      VARCHAR(2);
ALTER TABLE SYS_PES ADD COLUMN IF NOT EXISTS PesTraSer        VARCHAR(5);
ALTER TABLE SYS_PES ADD COLUMN IF NOT EXISTS PesTraNum        VARCHAR(7);
ALTER TABLE SYS_PES ADD COLUMN IF NOT EXISTS PesTraEst        CHAR(2);
ALTER TABLE SYS_PES ADD COLUMN IF NOT EXISTS PesTraDat        DATE;
ALTER TABLE SYS_PES ADD COLUMN IF NOT EXISTS PesTraPis        CHAR(11);
ALTER TABLE SYS_PES ADD COLUMN IF NOT EXISTS PesEleNum        VARCHAR(13);
ALTER TABLE SYS_PES ADD COLUMN IF NOT EXISTS PesEleZon        VARCHAR(4);
ALTER TABLE SYS_PES ADD COLUMN IF NOT EXISTS PesEleSec        VARCHAR(4);
ALTER TABLE SYS_PES ADD COLUMN IF NOT EXISTS PesNumSoc        CHAR(11);
ALTER TABLE SYS_PES ADD COLUMN IF NOT EXISTS PesFreEsc        CHAR(1);
ALTER TABLE SYS_PES ADD COLUMN IF NOT EXISTS PesGraEsc        SMALLINT;
ALTER TABLE SYS_PES ADD COLUMN IF NOT EXISTS PesEscolaridade  SMALLINT;
ALTER TABLE SYS_PES ADD COLUMN IF NOT EXISTS PesCborCod       CHAR(6);
ALTER TABLE SYS_PES ADD COLUMN IF NOT EXISTS PesCadDat        DATE;
ALTER TABLE SYS_PES ADD COLUMN IF NOT EXISTS PesObs           VARCHAR(300);
ALTER TABLE SYS_PES ADD COLUMN IF NOT EXISTS PesGerBpa        SMALLINT;

-- Minimal lookup stubs for the FK-existence checks (R25/R34/R47). Present in the live DB already
-- (no-op there); created here so the R-existence probes are valid against the local/Testcontainers
-- schema. Full definitions belong to their own leaf slices.
CREATE TABLE IF NOT EXISTS SAU_ETN (
    EtnCod  SMALLINT NOT NULL,
    EtnNom  VARCHAR(60),
    CONSTRAINT pk_sau_etn PRIMARY KEY (EtnCod)
);
CREATE TABLE IF NOT EXISTS SAU_PAIS (
    PaisCod SMALLINT NOT NULL,
    PaisNom VARCHAR(60),
    CONSTRAINT pk_sau_pais PRIMARY KEY (PaisCod)
);
CREATE TABLE IF NOT EXISTS SAU_ORGEMI (
    OrgEmiCod INTEGER NOT NULL,
    OrgEmiDes VARCHAR(60),
    CONSTRAINT pk_sau_orgemi PRIMARY KEY (OrgEmiCod)
);
