-- SAU_USUUNI (Usuário × Unidade) — promote the minimal stub (PK was UsuCod-only, no flags) to the
-- full per-(user,unit) capability matrix. 54 native BOOLEAN flags (49 Bloq* block + 5 Per* permit),
-- verified against the live saude-mandaguari DB (which already has them → every ADD is a no-op there).
-- UsuUniEspCod: optional FK → SAU_ESP.EspCod (auditor specialty). Idempotent.
ALTER TABLE SAU_USUUNI ADD COLUMN IF NOT EXISTS UsuUniEspCod INTEGER;
ALTER TABLE SAU_USUUNI ADD COLUMN IF NOT EXISTS UsuUniBloqTab BOOLEAN;
ALTER TABLE SAU_USUUNI ADD COLUMN IF NOT EXISTS UsuUniBloqCad BOOLEAN;
ALTER TABLE SAU_USUUNI ADD COLUMN IF NOT EXISTS UsuUniBloqAmb BOOLEAN;
ALTER TABLE SAU_USUUNI ADD COLUMN IF NOT EXISTS UsuUniPerConDir BOOLEAN;
ALTER TABLE SAU_USUUNI ADD COLUMN IF NOT EXISTS UsuUniBloqPrtCon BOOLEAN;
ALTER TABLE SAU_USUUNI ADD COLUMN IF NOT EXISTS UsuUniBloqPrtOdo BOOLEAN;
ALTER TABLE SAU_USUUNI ADD COLUMN IF NOT EXISTS UsuUniBloqResExa BOOLEAN;
ALTER TABLE SAU_USUUNI ADD COLUMN IF NOT EXISTS UsuUniBloqEsus BOOLEAN;
ALTER TABLE SAU_USUUNI ADD COLUMN IF NOT EXISTS UsuUniBloqCaps BOOLEAN;
ALTER TABLE SAU_USUUNI ADD COLUMN IF NOT EXISTS UsuUniBloqNut BOOLEAN;
ALTER TABLE SAU_USUUNI ADD COLUMN IF NOT EXISTS UsuUniBloqFar BOOLEAN;
ALTER TABLE SAU_USUUNI ADD COLUMN IF NOT EXISTS UsuUniPerBnafar BOOLEAN;
ALTER TABLE SAU_USUUNI ADD COLUMN IF NOT EXISTS UsuUniBloqAlm BOOLEAN;
ALTER TABLE SAU_USUUNI ADD COLUMN IF NOT EXISTS UsuUniBloqReq BOOLEAN;
ALTER TABLE SAU_USUUNI ADD COLUMN IF NOT EXISTS UsuUniBloqBen BOOLEAN;
ALTER TABLE SAU_USUUNI ADD COLUMN IF NOT EXISTS UsuUniBloqTra BOOLEAN;
ALTER TABLE SAU_USUUNI ADD COLUMN IF NOT EXISTS UsuUniBloqVac BOOLEAN;
ALTER TABLE SAU_USUUNI ADD COLUMN IF NOT EXISTS UsuUniBloqAge BOOLEAN;
ALTER TABLE SAU_USUUNI ADD COLUMN IF NOT EXISTS UsuUniBloqAgeMan BOOLEAN;
ALTER TABLE SAU_USUUNI ADD COLUMN IF NOT EXISTS UsuUniBloqAgeExt BOOLEAN;
ALTER TABLE SAU_USUUNI ADD COLUMN IF NOT EXISTS UsuUniBloqAgeEsp BOOLEAN;
ALTER TABLE SAU_USUUNI ADD COLUMN IF NOT EXISTS UsuUniPerAgeAud BOOLEAN;
ALTER TABLE SAU_USUUNI ADD COLUMN IF NOT EXISTS UsuUniBloqLab BOOLEAN;
ALTER TABLE SAU_USUUNI ADD COLUMN IF NOT EXISTS UsuUniBloqHos BOOLEAN;
ALTER TABLE SAU_USUUNI ADD COLUMN IF NOT EXISTS UsuUniBloqVig BOOLEAN;
ALTER TABLE SAU_USUUNI ADD COLUMN IF NOT EXISTS UsuUniBloqAgr BOOLEAN;
ALTER TABLE SAU_USUUNI ADD COLUMN IF NOT EXISTS UsuUniBloqCMS BOOLEAN;
ALTER TABLE SAU_USUUNI ADD COLUMN IF NOT EXISTS UsuUniBloqOuv BOOLEAN;
ALTER TABLE SAU_USUUNI ADD COLUMN IF NOT EXISTS UsuUniBloqImp BOOLEAN;
ALTER TABLE SAU_USUUNI ADD COLUMN IF NOT EXISTS UsuUniBloqExp BOOLEAN;
ALTER TABLE SAU_USUUNI ADD COLUMN IF NOT EXISTS UsuUniBloqPar BOOLEAN;
ALTER TABLE SAU_USUUNI ADD COLUMN IF NOT EXISTS UsuUniBloqRel BOOLEAN;
ALTER TABLE SAU_USUUNI ADD COLUMN IF NOT EXISTS UsuUniBloqRelTab BOOLEAN;
ALTER TABLE SAU_USUUNI ADD COLUMN IF NOT EXISTS UsuUniBloqRelCad BOOLEAN;
ALTER TABLE SAU_USUUNI ADD COLUMN IF NOT EXISTS UsuUniBloqRelAmb BOOLEAN;
ALTER TABLE SAU_USUUNI ADD COLUMN IF NOT EXISTS UsuUniBloqRelEsus BOOLEAN;
ALTER TABLE SAU_USUUNI ADD COLUMN IF NOT EXISTS UsuUniBloqRelCaps BOOLEAN;
ALTER TABLE SAU_USUUNI ADD COLUMN IF NOT EXISTS UsuUniBloqRelNut BOOLEAN;
ALTER TABLE SAU_USUUNI ADD COLUMN IF NOT EXISTS UsuUniBloqRelVac BOOLEAN;
ALTER TABLE SAU_USUUNI ADD COLUMN IF NOT EXISTS UsuUniBloqRelFar BOOLEAN;
ALTER TABLE SAU_USUUNI ADD COLUMN IF NOT EXISTS UsuUniBloqRelAlm BOOLEAN;
ALTER TABLE SAU_USUUNI ADD COLUMN IF NOT EXISTS UsuUniBloqRelReq BOOLEAN;
ALTER TABLE SAU_USUUNI ADD COLUMN IF NOT EXISTS UsuUniBloqRelBen BOOLEAN;
ALTER TABLE SAU_USUUNI ADD COLUMN IF NOT EXISTS UsuUniBloqRelTra BOOLEAN;
ALTER TABLE SAU_USUUNI ADD COLUMN IF NOT EXISTS UsuUniBloqRelAge BOOLEAN;
ALTER TABLE SAU_USUUNI ADD COLUMN IF NOT EXISTS UsuUniBloqRelLab BOOLEAN;
ALTER TABLE SAU_USUUNI ADD COLUMN IF NOT EXISTS UsuUniBloqRelHos BOOLEAN;
ALTER TABLE SAU_USUUNI ADD COLUMN IF NOT EXISTS UsuUniBloqRelVig BOOLEAN;
ALTER TABLE SAU_USUUNI ADD COLUMN IF NOT EXISTS UsuUniBloqRelAgr BOOLEAN;
ALTER TABLE SAU_USUUNI ADD COLUMN IF NOT EXISTS UsuUniBloqRelOuv BOOLEAN;
ALTER TABLE SAU_USUUNI ADD COLUMN IF NOT EXISTS UsuUniBloqRelExp BOOLEAN;
ALTER TABLE SAU_USUUNI ADD COLUMN IF NOT EXISTS UsuUniBloqGra BOOLEAN;
ALTER TABLE SAU_USUUNI ADD COLUMN IF NOT EXISTS UsuUniPerAgeAudPcd BOOLEAN;
ALTER TABLE SAU_USUUNI ADD COLUMN IF NOT EXISTS UsuUniPerSoaBnafar BOOLEAN;

-- Fix the composite PK. The baseline stub declared PRIMARY KEY (UsuCod) only; the real key is
-- (UsuCod, UniUsuCod). Do this ONLY where the current PK is the single-column stub (local/Testcontainers);
-- on the live DB the PK is already composite, so this block is skipped (no-op).
DO $$
DECLARE pkcols text; pkname text;
BEGIN
  SELECT string_agg(a.attname, ',' ORDER BY array_position(c.conkey, a.attnum)), c.conname
    INTO pkcols, pkname
  FROM pg_constraint c
  JOIN pg_attribute a ON a.attrelid = c.conrelid AND a.attnum = ANY(c.conkey)
  WHERE c.conrelid = 'sau_usuuni'::regclass AND c.contype = 'p'
  GROUP BY c.conname;
  IF pkcols = 'usucod' THEN
    ALTER TABLE SAU_USUUNI ALTER COLUMN UniUsuCod SET NOT NULL;
    EXECUTE 'ALTER TABLE SAU_USUUNI DROP CONSTRAINT ' || quote_ident(pkname);
    ALTER TABLE SAU_USUUNI ADD CONSTRAINT pk_sau_usuuni PRIMARY KEY (UsuCod, UniUsuCod);
  END IF;
END $$;
