package br.gov.mandaguari.saude.unidade.dto;

import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Size;

public class UnidadeDtos {

    public record UnidadeCreateRequest(
            @NotBlank @Size(max = 50) String nome,
            @Size(max = 50) String razaoSocial,
            @NotBlank @Size(max = 18) String cnpj,
            @NotBlank @Size(max = 8) String cep,
            @NotBlank @Size(max = 70) String endereco,
            @NotBlank @Size(max = 10) String enderecoNumero,
            @Size(max = 40) String enderecoComplemento,
            @NotBlank @Size(max = 70) String bairro,
            @Size(max = 20) String telefone,
            @Size(max = 20) String fax,
            @Size(max = 10) String licencaFuncionamento,
            @Size(max = 50) String responsavel,
            @Size(max = 70) String email,
            Integer cnes,
            Short bpa,
            Short sipni,
            @Size(max = 10) String orgaoEmissor,
            Short estrategiaFamiliar,
            Short psf,
            Short sisPreNatal,
            Short hiperdia,
            Short gestao,
            @Size(max = 7) String sia,
            @Size(max = 6) String sigla,
            Short situacao,
            @Size(max = 7) String siaSus,
            @Size(max = 20) String scnesId,
            Boolean exportarEsus,
            Boolean exportarBnafar,
            Boolean cadastroCns,
            Boolean cadastroEndereco,
            Boolean atendimentoSemCns,
            Boolean atendimentoSemEndereco,
            Boolean encaminhamentoFisioterapia,
            Boolean externo,
            Long forPesCod,
            Integer tipoUnidadeCodigo,
            Boolean atencaoSecundaria,
            Boolean bloqueioPacSemCadInd,
            Boolean avisoVacinaAtrasada,
            Boolean cadastroCpf,
            Boolean painel,
            Boolean recepcaoIntermedMpp,
            Boolean recepcaoIntermedMppImp,
            Boolean baixaRemSemCns,
            Boolean bloqueioLancPcdAut,
            Boolean bloqueioDispPacExt,
            Boolean bloqueioAgendSolExaPacExt,
            Integer municipioCodigo,
            Long respProfissionalCodigo,
            Long diretorCodigo,
            Long auditorCodigo,
            Long autorizadorCodigo,
            Short distritoCodigo
    ) {}

    public record UnidadeUpdateRequest(
            @NotBlank @Size(max = 50) String nome,
            @Size(max = 50) String razaoSocial,
            @NotBlank @Size(max = 18) String cnpj,
            @NotBlank @Size(max = 8) String cep,
            @NotBlank @Size(max = 70) String endereco,
            @NotBlank @Size(max = 10) String enderecoNumero,
            @Size(max = 40) String enderecoComplemento,
            @NotBlank @Size(max = 70) String bairro,
            @Size(max = 20) String telefone,
            @Size(max = 20) String fax,
            @Size(max = 10) String licencaFuncionamento,
            @Size(max = 50) String responsavel,
            @Size(max = 70) String email,
            Integer cnes,
            Short bpa,
            Short sipni,
            @Size(max = 10) String orgaoEmissor,
            Short estrategiaFamiliar,
            Short psf,
            Short sisPreNatal,
            Short hiperdia,
            Short gestao,
            @Size(max = 7) String sia,
            @Size(max = 6) String sigla,
            Short situacao,
            @Size(max = 7) String siaSus,
            @Size(max = 20) String scnesId,
            Boolean exportarEsus,
            Boolean exportarBnafar,
            Boolean cadastroCns,
            Boolean cadastroEndereco,
            Boolean atendimentoSemCns,
            Boolean atendimentoSemEndereco,
            Boolean encaminhamentoFisioterapia,
            Boolean externo,
            Long forPesCod,
            Integer tipoUnidadeCodigo,
            Boolean atencaoSecundaria,
            Boolean bloqueioPacSemCadInd,
            Boolean avisoVacinaAtrasada,
            Boolean cadastroCpf,
            Boolean painel,
            Boolean recepcaoIntermedMpp,
            Boolean recepcaoIntermedMppImp,
            Boolean baixaRemSemCns,
            Boolean bloqueioLancPcdAut,
            Boolean bloqueioDispPacExt,
            Boolean bloqueioAgendSolExaPacExt,
            Integer municipioCodigo,
            Long respProfissionalCodigo,
            Long diretorCodigo,
            Long auditorCodigo,
            Long autorizadorCodigo,
            Short distritoCodigo
    ) {}

    public record UnidadeResponse(
            Integer codigo,
            String nome,
            String razaoSocial,
            String cnpj,
            String cep,
            String endereco,
            String enderecoNumero,
            String enderecoComplemento,
            String bairro,
            String telefone,
            String fax,
            String licencaFuncionamento,
            String responsavel,
            String email,
            Integer cnes,
            Short bpa,
            Short sipni,
            String orgaoEmissor,
            Short estrategiaFamiliar,
            Short psf,
            Short sisPreNatal,
            Short hiperdia,
            Short gestao,
            String sia,
            String sigla,
            Short situacao,
            String siaSus,
            String scnesId,
            Boolean exportarEsus,
            Boolean exportarBnafar,
            Boolean cadastroCns,
            Boolean cadastroEndereco,
            Boolean atendimentoSemCns,
            Boolean atendimentoSemEndereco,
            Boolean encaminhamentoFisioterapia,
            Boolean externo,
            Long forPesCod,
            Integer tipoUnidadeCodigo,
            Boolean atencaoSecundaria,
            Boolean bloqueioPacSemCadInd,
            Boolean avisoVacinaAtrasada,
            Boolean cadastroCpf,
            Boolean painel,
            Boolean recepcaoIntermedMpp,
            Boolean recepcaoIntermedMppImp,
            Boolean baixaRemSemCns,
            Boolean bloqueioLancPcdAut,
            Boolean bloqueioDispPacExt,
            Boolean bloqueioAgendSolExaPacExt,
            Integer municipioCodigo,
            Long respProfissionalCodigo,
            Long diretorCodigo,
            Long auditorCodigo,
            Long autorizadorCodigo,
            Short distritoCodigo
    ) {}

    public record UnidadeLookupItem(Integer codigo, String nome) {}
}
